// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VEA.Infrastructure.EfcPersistence.Common;

#nullable disable

namespace VEA.Infrastructure.EfcPersistence.Migrations
{
    [DbContext(typeof(EfcWriteDbContext))]
    partial class EfcWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("VEA.Core.Domain.Aggregates.GuestAggregate.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ViaMail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("VEA.Core.Domain.Aggregates.VeaEventAggregate.ParticipationEntity.Participation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("GuestId");

                    b.ToTable("Participation");
                });

            modelBuilder.Entity("VEA.Core.Domain.Aggregates.VeaEventAggregate.VeaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GuestCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("VEA.Core.Domain.Aggregates.VeaEventAggregate.ParticipationEntity.Participation", b =>
                {
                    b.HasOne("VEA.Core.Domain.Aggregates.VeaEventAggregate.VeaEvent", null)
                        .WithMany("_participations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VEA.Core.Domain.Aggregates.GuestAggregate.Guest", null)
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VEA.Core.Domain.Aggregates.VeaEventAggregate.VeaEvent", b =>
                {
                    b.OwnsOne("VEA.Core.Domain.Aggregates.VeaEventAggregate.EventTimeRange", "TimeRange", b1 =>
                        {
                            b1.Property<Guid>("VeaEventId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("End")
                                .HasColumnType("TEXT")
                                .HasColumnName("TimeRangeEnd");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("TEXT")
                                .HasColumnName("TimeRangeStart");

                            b1.HasKey("VeaEventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("VeaEventId");
                        });

                    b.Navigation("TimeRange");
                });

            modelBuilder.Entity("VEA.Core.Domain.Aggregates.VeaEventAggregate.VeaEvent", b =>
                {
                    b.Navigation("_participations");
                });
#pragma warning restore 612, 618
        }
    }
}
